"""Ajout de already_answered

Revision ID: 3658bd1ee333
Revises: 
Create Date: 2025-03-12 10:25:44.801232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3658bd1ee333'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('res_currency')
    op.drop_table('res_country')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('already_answered', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('emails_mail_type_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'mail_type', ['mail_type_id'], ['id'])

    with op.batch_alter_table('emails_partner', schema=None) as batch_op:
        batch_op.drop_constraint('emails_partner_emails_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('emails_partner_partner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'res_partner', ['partner_id'], ['id'])
        batch_op.create_foreign_key(None, 'emails', ['emails_id'], ['id'])

    with op.batch_alter_table('emails_state', schema=None) as batch_op:
        batch_op.drop_constraint('emails_state_emails_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'emails', ['emails_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails_state', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emails_state_emails_id_fkey', 'emails', ['emails_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('emails_partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emails_partner_partner_id_fkey', 'res_partner', ['partner_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('emails_partner_emails_id_fkey', 'emails', ['emails_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('emails_mail_type_id_fkey', 'mail_type', ['mail_type_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('already_answered')

    op.create_table('res_country',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='res_country_pkey'),
    sa.UniqueConstraint('code', name='res_country_code_key')
    )
    op.create_table('res_currency',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='res_currency_pkey')
    )
    # ### end Alembic commands ###
